### ISSUE TITLE
All CGO implementations can be faster if used with `LockOSThread`

### ISSUE THREAD

**Issue by ngortheone** [cvilsmeier/go-sqlite-bench#11]
An author of the vulkan wrapper library for go suggests that most CGO-related slowness is caused by C function calls disrupting golang's scheduler.  This can mostly be mitigated by using `runtime.LockOSThread`  for the goroutine that does sqlite calls.

I believe this can dramatically improve `mattn` library performance in most benchmarks.

-----
https://www.reddit.com/r/golang/comments/12nt2le/comment/jgmfhzj/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

https://pkg.go.dev/runtime#LockOSThread

P.S. I found this repo via https://golangweekly.com/issues/536 :D

**Comment by ncruces** [comment]
Then maybe you should open an issue on `mattn` (and others)?

It makes no sense for the consumer of a `database/sql` driver to worry about this.

**Comment by dcarbone** [comment]
> Perhaps. But there is a logical contradiction in your suggestion. We can't state that `mattn` library should do anything before we show benchmark results that show the effect of suggested improvement.

It is not the responsibility of this project nor its owner to do that.  Perhaps run the benchmarks available here yourself with an A:B comparison of with and without flag, opening a suggestive PR on mattn's project with the results if they show positive results?

**Comment by ngortheone** [comment]
I am trying to do that currently  and I am facing an issue (perhaps worth opening a separate issue?)

```
 (I) ~/tmp/go-sqlite-bench ./build-all.sh      
                        master 
build craw
build eaton
go: downloading github.com/eatonphil/gosqlite v0.10.0
# github.com/cvilsmeier/go-sqlite-bench/cmd/bench-eaton
/home/ngor/app/go/pkg/tool/freebsd_amd64/link: running clang failed: exit status 1
/usr/bin/clang -m64 -o $WORK/b001/exe/a.out -Wl,--export-dynamic-symbol=__progname -Wl,--export-dynamic-symbol=_cgo_panic -Wl,--export-dynamic-symbol=_cgo_topofstack -Wl,--export-dynamic-symbol=crosscall2 -Wl,--export-dynamic-symbol=environ -Wl,--export-dynamic-symbol=go_busy_handler -Wl,--export-dynamic-symbol=go_commit_hook -Wl,--export-dynamic-symbol=go_rollback_hook -Wl,--export-dynamic-symbol=go_set_authorizer -Wl,--export-dynamic-symbol=go_update_hook -Wl,--export-dynamic-symbol=strm_r_tramp -Wl,--export-dynamic-symbol=strm_w_tramp -Wl,--export-dynamic-symbol=xapply_conflict_tramp -Wl,--export-dynamic-symbol=xapply_filter_tramp -Qunused-arguments -Wl,--compress-debug-sections=zlib /tmp/go-link-799608693/go.o /tmp/go-link-799608693/000000.o /tmp/go-link-799608693/000001.o /tmp/go-link-799608693/000002.o /tmp/go-link-799608693/000003.o /tmp/go-link-799608693/000004.o /tmp/go-link-799608693/000005.o /tmp/go-link-799608693/000006.o /tmp/go-link-799608693/000007.o /tmp/go-link-799608693/000008.o /tmp/go-link-799608693/000009.o /tmp/go-link-799608693/000010.o /tmp/go-link-799608693/000011.o /tmp/go-link-799608693/000012.o /tmp/go-link-799608693/000013.o /tmp/go-link-799608693/000014.o /tmp/go-link-799608693/000015.o /tmp/go-link-799608693/000016.o /tmp/go-link-799608693/000017.o /tmp/go-link-799608693/000018.o /tmp/go-link-799608693/000019.o -O2 -g -O2 -g -lpthread -no-pie
ld: error: undefined symbol: log
>>> referenced by sqlite3.c:235142
>>>               /tmp/go-link-799608693/000007.o:(fts5Bm25Function)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cvilsmeier** [comment]
I ran the mattn single-goroutine benchmarks with and without LockOSThread (LOT). I ran each benchmark three times and took the average of the second and third run. Here are the results (lower numbers are better):
~~~
                           withoutLOT    withLOT
1_simple - insert                1628       1655
1_simple - query                 1136       1157
2_complex - insert                902        914
2_complex - query                1268       1249
3_many/0010 - insert                9          9
3_many/0010 - query                31         31
3_many/0100 - insert               10          8
3_many/0100 - query              112         120
3_many/1000 - insert               14         14
3_many/1000 - query              1033       1035
4_large/050000 - insert           698        709
4_large/050000 - query            152        162
4_large/100000 - insert          1282       1288
4_large/100000 - query            249        271
4_large/200000 - insert          2380       2531
4_large/200000 - query            536        502
~~~
As you can see, on my machine and using go1.23.4, calling LockOSThread does not make a significant difference in performance. In most cases, withLOT is even slower than withoutLOT. So I will close the issue.

**Comment by ngortheone** [comment]
@cvilsmeier thanks for verifying this!
