### ISSUE TITLE
How do you run tests?

### ISSUE THREAD

**Issue by delaneyj** [cvilsmeier/go-sqlite-bench#2]
`all.sh` doesn't have any commands

**Comment by cvilsmeier** [comment]
Oops, that was a mistake, I checked in the corrrect scripts, see `build-all.sh` and `run-all.sh`

**Comment by delaneyj** [comment]
@cvilsmeier  but what about generating graphs?

**Comment by cvilsmeier** [comment]
I didn't automate generating graphs. I capture the output and manually transfer the numbers into a spreadsheet to make charts.
